yarnPath: .yarn/releases/yarn-4.12.0.cjs

# For compatibility with Turbo and the broad JS ecosystem
nodeLinker: node-modules

# The best default for monorepos: reduces phantom-dep leakage across workspaces
nmHoistingLimits: workspaces
#nmHoistingLimits: dependencies

# Good defaults for deterministic CI and fewer “works locally” surprises
checksumBehavior: throw
enableImmutableInstalls: false

# Usually helps performance and keeps installs consistent across machines/CI
enableGlobalCache: true
compressionLevel: mixed

# Prefer a node_modules layout that plays nicely with tooling and symlinks
nmMode: hardlinks-local
tsEnableAutoTypes: true
preferReuse: true
enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0086
    level: discard

packageExtensions:
  "@azure/storage-common@*":
    dependencies:
      "@azure/core-client": "^1.10.0"
  "@modelcontextprotocol/sdk@*":
    dependencies:
      hono: "^4.0.0"
  "@toolpad/core@*":
    dependencies:
      "@mui/system": "^7.0.0"
      vite: "^4.2.0 || ^5.0.0 || ^6.0.0"
  "babel-plugin-transform-flow-enums@*":
    dependencies:
      "@babel/core": "^7.8.0"
  "babel-preset-expo@*":
    dependencies:
      "@babel/core": "^7.8.0"
  "otlp-logger@*":
    dependencies:
      "@opentelemetry/api": ">=1.4.0 <1.10.0"
  "react-native@*":
    dependencies:
      "@babel/core": "^7.8.0"
