yarnPath: .yarn/releases/yarn-4.12.0.cjs

# For compatibility with Turbo and the broad JS ecosystem
nodeLinker: node-modules

# The best default for monorepos: reduces phantom-dep leakage across workspaces
nmHoistingLimits: workspaces
#nmHoistingLimits: dependencies

# Good defaults for deterministic CI and fewer “works locally” surprises
checksumBehavior: throw
enableImmutableInstalls: true

# Usually helps performance and keeps installs consistent across machines/CI
enableGlobalCache: true
compressionLevel: mixed

# Prefer a node_modules layout that plays nicely with tooling and symlinks
nmMode: hardlinks-local
