packages:
  - 'web-ui/packages/**'
  - 'codex-mcp'
  - 'web-ui/submodules/json-viewer/packages'
  - '!web-ui/submodules/json-viewer/packages/docs'
  - 'web-ui/submodules/sce'
  - 'web-ui/submodules/sce/packages/**/ts'
