/**
 * @fileoverview Type definitions for Redis cache middleware
 */

import type { LanguageModelV2Content } from '@ai-sdk/provider';

declare module '@/lib/ai/middleware/cacheWithRedis/types' {
  /**
   * Represents a cacheable AI response with all relevant metadata.
   *
   * This structure is used to store the response from the AI model in the Redis cache,
   * preserving not just the content but also metadata like usage statistics and finish reasons.
   */
  export interface CacheableResponse {
    /**
     * Unique identifier for the response.
     */
    id: string;

    /**
     * The content generated by the language model.
     */
    content: Array<LanguageModelV2Content>;

    /**
     * The reason why the generation finished (e.g., 'stop', 'length', 'content-filter').
     */
    finishReason?: string;

    /**
     * Usage statistics for the generation (token counts, etc.).
     */
    usage?: Record<string, unknown>;

    /**
     * Any warnings returned by the model provider during generation.
     */
    warnings?: unknown[];

    /**
     * The raw call object used to make the request (optional).
     */
    rawCall?: unknown;

    /**
     * The raw response object received from the provider (optional).
     */
    rawResponse?: unknown;

    /**
     * The parsed response object (optional).
     */
    response?: unknown;
  }

  /**
   * Represents an entry in the cache jail system for problematic responses.
   *
   * The jail system tracks responses that are frequently requested but result in errors or
   * undesirable outcomes, allowing the system to "jail" (cache) them to prevent repeated
   * expensive failures.
   */
  export interface JailEntry {
    /**
     * The number of times this specific request has been seen.
     */
    count: number;

    /**
     * Timestamp (ms) when this request was first seen.
     */
    firstSeen: number;

    /**
     * Timestamp (ms) when this request was last seen.
     */
    lastSeen?: number;

    /**
     * Information about the last response received for this request.
     */
    lastResponse?: {
      /**
       * The finish reason of the last response.
       */
      finishReason: string;

      /**
       * Whether the last response had warnings.
       */
      hasWarnings: boolean;

      /**
       * The length of the generated text in the last response.
       */
      textLength: number;
    };
  }
}
