package com.obapps.schoolchatbot.core.assistants.services;

import dev.langchain4j.model.chat.ChatLanguageModel;

/**
 * Interface representing a standalone model client for interacting with a model.
 * Provides a method to send a prompt and receive a response.
 */
public interface IStandaloneModelClient {
  /**
   * Sends a prompt to the model and retrieves the response.
   *
   * @param prompt The input string to be sent to the model.
   * @return The response generated by the model as a string.
   */
  String call(String prompt);

  /**
   * Retrieves the chat language model instance.
   *
   * @return an instance of {@link ChatLanguageModel} representing the chat language model.
   */
  ChatLanguageModel getModel();
}
