import React from 'react';

export default React;

export {
	act,
	Children,
	cloneElement,
	Component,
	createContext,
	createElement,
	createRef,
	forwardRef,
	Fragment,
	lazy,
	memo,
	Profiler,
	PureComponent,
	startTransition,
	StrictMode,
	Suspense,
	use,
	useActionState,
	useCallback,
	useContext,
	useDebugValue,
	useDeferredValue,
	useEffect,
	useId,
	useImperativeHandle,
	useInsertionEffect,
	useLayoutEffect,
	useMemo,
	useOptimistic,
	useReducer,
	useRef,
	useState,
	useSyncExternalStore,
	useTransition,
} from 'react';

export type {
	ChangeEvent,
	ComponentProps,
	ComponentPropsWithRef,
	ComponentPropsWithoutRef,
	ComponentType,
	Context,
	ContextType,
	CSSProperties,
	DependencyList,
	DetailedHTMLProps,
	Dispatch,
	DispatchWithoutAction,
	ElementType,
	ErrorInfo,
	FC,
	FormEvent,
	ForwardRefRenderFunction,
	FunctionComponent,
	HTMLAttributes,
	JSX,
	JSXElementConstructor,
	KeyboardEvent,
	Key,
	MemoExoticComponent,
	MouseEvent,
	MutableRefObject,
	PropsWithChildren,
	PropsWithoutRef,
	ReactElement,
	ReactNode,
	Ref,
	RefAttributes,
	RefCallback,
	RefObject,
	SetStateAction,
	SyntheticEvent,
	TouchEvent,
	WheelEvent,
} from 'react';
