/**
 * Main entry point for Drizzle DB functionality
 * @module @/lib/drizzle-db
 */

import type {
  DatabaseType,
  SchemaType,
  DocumentUnitType,
  DocumentPropertyType,
  DocumentPropertyTypeType,
  DocumentRelationshipType,
  EmailType,
  EmailAttachmentType,
  KeyPointType,
  CallToActionType,
  CallToActionCategoryType,
  CallToActionResponseType,
  CallToActionResponsiveActionLinkType,
  ChatMessagesType,
  ChatsType,
  ChatTurnsType,
  UserPublicKeysType,
  ViolationDetailsType,
  ComplianceScoreType,
  QueryBuilders,
  DocumentUnitQueryShape,
  DocumentPropertyQueryShape,
  EmailQueryShape,
  EmailAttachmentQueryShape,
  KeyPointQueryShape,
  CallToActionQueryShape,
  CallToActionCategoryQueryShape,
  CallToActionResponseQueryShape,
  ViolationDetailsQueryShape,
  ComplianceScoresDetailsQueryShape,
  ProvidersType,
  ModelsType,
  ModelQuotasType,
  Types,
} from './drizzle-types';

import type {
  DbFullSchemaType,
  DbSchemaType,
  DbDatabaseType,
  DbQueryResultHKT,
  DbTransactionType,
} from './schema';

import type { schema, drizDbWithInit, drizDb } from './connection';
import type {
  getDocumentRelationReason,
  addDocumentRelations,
  addNotesToDocument,
} from './db-helpers';
import type { sql, DrizzleSqlType } from './drizzle-sql';

declare module '@/lib/drizzle-db' {
  export type {
    DatabaseType,
    SchemaType,
    DocumentUnitType,
    DocumentPropertyType,
    DocumentPropertyTypeType,
    DocumentRelationshipType,
    EmailType,
    EmailAttachmentType,
    KeyPointType,
    CallToActionType,
    CallToActionCategoryType,
    CallToActionResponseType,
    CallToActionResponsiveActionLinkType,
    ChatMessagesType,
    ChatsType,
    ChatTurnsType,
    UserPublicKeysType,
    ViolationDetailsType,
    ComplianceScoreType,
    QueryBuilders,
    DocumentUnitQueryShape,
    DocumentPropertyQueryShape,
    EmailQueryShape,
    EmailAttachmentQueryShape,
    KeyPointQueryShape,
    CallToActionQueryShape,
    CallToActionCategoryQueryShape,
    CallToActionResponseQueryShape,
    ViolationDetailsQueryShape,
    ComplianceScoresDetailsQueryShape,
    ProvidersType,
    ModelsType,
    ModelQuotasType,
    Types,
    DbFullSchemaType,
    DbSchemaType,
    DbDatabaseType,
    DbQueryResultHKT,
    DbTransactionType,
    schema,
    drizDbWithInit,
    drizDb,
    getDocumentRelationReason,
    addDocumentRelations,
    addNotesToDocument,
    sql,
    DrizzleSqlType,
  };
}
