nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

logFilters:
  - code: YN0060
    text: "(p2f21e7)"
    level: discard
  - code: YN0060
    text: "(pbcbe0f)"
    level: discard
  - code: YN0060
    text: "(p5743a1)"
    level: discard
  - code: YN0086
    text: "Some peer dependencies are incorrectly met by your project"
    level: discard
