name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

env:
  NEXT_PUBLIC_HOSTNAME: ${{ vars.NEXT_PUBLIC_HOSTNAME }}
  NEXT_PUBLIC_LOG_LEVEL_CLIENT: ${{ vars.NEXT_PUBLIC_LOG_LEVEL_CLIENT }}
  NEXT_PUBLIC_DEFAULT_AI_MODEL: ${{ vars.NEXT_PUBLIC_DEFAULT_AI_MODEL }}
  AZURE_MONITOR_CONNECTION_STRING: ${{ secrets.NEXT_PUBLIC_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING }}
  NEXT_PUBLIC_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.NEXT_PUBLIC_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_KEYCLOAK_CLIENT_ID: ${{ secrets.AUTH_KEYCLOAK_CLIENT_ID }}
  AUTH_KEYCLOAK_CLIENT_SECRET: ${{ secrets.AUTH_KEYCLOAK_CLIENT_SECRET }}
  AUTH_KEYCLOAK_ISSUER: ${{ secrets.AUTH_KEYCLOAK_ISSUER }}
  AUTH_KEYCLOAK_IMPERSONATOR_USERNAME: ${{ secrets.AUTH_KEYCLOAK_IMPERSONATOR_USERNAME }}
  AUTH_KEYCLOAK_IMPERSONATOR_PASSWORD: ${{ secrets.AUTH_KEYCLOAK_IMPERSONATOR_PASSWORD }}
  COPILOT_LOGIN_PASSWORD: ${{ secrets.COPILOT_LOGIN_PASSWORD }}
  COPILOT_LOGIN_USER: ${{ vars.COPILOT_LOGIN_USER }}
  NEXT_PUBLIC_FLAGSMITH_API_URL: ${{ vars.NEXT_PUBLIC_FLAGSMITH_API_URL }}
  NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID: ${{ vars.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID }}
  FLAGSMITH_SDK_KEY: ${{ secrets.FLAGSMITH_SDK_KEY }}
  MEM0_API_HOST: ${{ vars.MEM0_API_HOST }}
  MEM0_UI_HOST: ${{ vars.MEM0_UI_HOST }}
  MEM0_DISABLED: false
  MEM0_PROJECT_ID: school-law
  NEXT_PUBLIC_AZURE_MONITOR_CONNECTION_STRING: ${{ vars.NEXT_PUBLIC_AZURE_MONITOR_CONNECTION_STRING }}
  AZURE_AISEARCH_ENDPOINT: ${{ secrets.AZURE_AISEARCH_ENDPOINT }}
  AZURE_AISEARCH_KEY: ${{ secrets.AZURE_AISEARCH_KEY }}
  AZURE_AISEARCH_DOCUMENTS_INDEX_NAME: documents_prod
  AZURE_AISEARCH_POLICY_INDEX_NAME: policy_units
  AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
  AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
  AZURE_OPENAI_DEPLOYMENT_EMBEDDING: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_EMBEDDING }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  NEXT_TELEMETRY_DISABLED: 1
  NEXT_PUBLIC_MUI_LICENSE: ${{ vars.NEXT_PUBLIC_MUI_LICENSE }}
  CRYPTO_KEYS_EC_P521_PRIVATE: ${{ secrets.CRYPTO_KEYS_EC_P521_PRIVATE }}
  CRYPTO_KEYS_EC_P521_PUBLIC: ${{ secrets.CRYPTO_KEYS_EC_P521_PUBLIC }}
  CRYPTO_KEYS_RSA_4096_PRIVATE: ${{ secrets.CRYPTO_KEYS_RSA_4096_PRIVATE }}
  CRYPTO_KEYS_RSA_4096_PUBLIC: ${{ secrets.CRYPTO_KEYS_RSA_4096_PUBLIC }}
  LOG_LEVEL: silly
  MCP_OTEL_MODE: DEBUG
  OPENAI_KEY_TEXT: "xxxxx"
  OTEL_SERVICE_NAME: "WebUI-CoPilot"
  OTEL_RESOURCE_ATTRIBUTES: service.namespace=ObApps.ComplianceTheatre,service.version=1.0,deployment.environment=CoPilot

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ">=22.13.1"
          cache: yarn
          cache-dependency-path: ./web-ui/yarn.lock

      - name: Run yarn install
        working-directory: ./web-ui
        run: yarn install --ignore-scripts --frozen-lockfile
        shell: bash
